//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_Usercontrol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess_Usercontrol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Black_B_1 {
            get {
                object obj = ResourceManager.GetObject("Black_B_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_B_2 {
            get {
                object obj = ResourceManager.GetObject("Black_B_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_B_3 {
            get {
                object obj = ResourceManager.GetObject("Black_B_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_B_4 {
            get {
                object obj = ResourceManager.GetObject("Black_B_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_B_5 {
            get {
                object obj = ResourceManager.GetObject("Black_B_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_0 {
            get {
                object obj = ResourceManager.GetObject("Black_C_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_1 {
            get {
                object obj = ResourceManager.GetObject("Black_C_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_1_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_1_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_1_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_1_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_2 {
            get {
                object obj = ResourceManager.GetObject("Black_C_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_2_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_2_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_2_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_2_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_3 {
            get {
                object obj = ResourceManager.GetObject("Black_C_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_3_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_3_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_3_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_3_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_4 {
            get {
                object obj = ResourceManager.GetObject("Black_C_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_4_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_4_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_4_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_4_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_5 {
            get {
                object obj = ResourceManager.GetObject("Black_C_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_5_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_5_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_5_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_5_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_6 {
            get {
                object obj = ResourceManager.GetObject("Black_C_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_6_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_6_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_6_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_6_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_7 {
            get {
                object obj = ResourceManager.GetObject("Black_C_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_7_Last {
            get {
                object obj = ResourceManager.GetObject("Black_C_7_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_C_7_Possible {
            get {
                object obj = ResourceManager.GetObject("Black_C_7_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_K_1 {
            get {
                object obj = ResourceManager.GetObject("Black_K_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_K_2 {
            get {
                object obj = ResourceManager.GetObject("Black_K_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_K_3 {
            get {
                object obj = ResourceManager.GetObject("Black_K_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_K_4 {
            get {
                object obj = ResourceManager.GetObject("Black_K_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_K_5 {
            get {
                object obj = ResourceManager.GetObject("Black_K_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_N_1 {
            get {
                object obj = ResourceManager.GetObject("Black_N_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_N_2 {
            get {
                object obj = ResourceManager.GetObject("Black_N_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_N_3 {
            get {
                object obj = ResourceManager.GetObject("Black_N_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_N_4 {
            get {
                object obj = ResourceManager.GetObject("Black_N_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_N_5 {
            get {
                object obj = ResourceManager.GetObject("Black_N_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_P_1 {
            get {
                object obj = ResourceManager.GetObject("Black_P_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_P_2 {
            get {
                object obj = ResourceManager.GetObject("Black_P_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_P_3 {
            get {
                object obj = ResourceManager.GetObject("Black_P_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_P_4 {
            get {
                object obj = ResourceManager.GetObject("Black_P_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_P_5 {
            get {
                object obj = ResourceManager.GetObject("Black_P_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_Q_1 {
            get {
                object obj = ResourceManager.GetObject("Black_Q_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_Q_2 {
            get {
                object obj = ResourceManager.GetObject("Black_Q_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_Q_3 {
            get {
                object obj = ResourceManager.GetObject("Black_Q_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_Q_4 {
            get {
                object obj = ResourceManager.GetObject("Black_Q_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_Q_5 {
            get {
                object obj = ResourceManager.GetObject("Black_Q_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_R_1 {
            get {
                object obj = ResourceManager.GetObject("Black_R_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_R_2 {
            get {
                object obj = ResourceManager.GetObject("Black_R_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_R_3 {
            get {
                object obj = ResourceManager.GetObject("Black_R_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_R_4 {
            get {
                object obj = ResourceManager.GetObject("Black_R_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_R_5 {
            get {
                object obj = ResourceManager.GetObject("Black_R_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Capture {
            get {
                return ResourceManager.GetStream("Capture", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Move {
            get {
                return ResourceManager.GetStream("Move", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Say_check {
            get {
                return ResourceManager.GetStream("Say_check", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Say_checkmate {
            get {
                return ResourceManager.GetStream("Say_checkmate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap White_B_1 {
            get {
                object obj = ResourceManager.GetObject("White_B_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_B_2 {
            get {
                object obj = ResourceManager.GetObject("White_B_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_B_3 {
            get {
                object obj = ResourceManager.GetObject("White_B_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_B_4 {
            get {
                object obj = ResourceManager.GetObject("White_B_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_B_5 {
            get {
                object obj = ResourceManager.GetObject("White_B_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_1 {
            get {
                object obj = ResourceManager.GetObject("White_C_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_1_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_1_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_1_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_1_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_2 {
            get {
                object obj = ResourceManager.GetObject("White_C_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_2_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_2_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_2_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_2_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_3 {
            get {
                object obj = ResourceManager.GetObject("White_C_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_3_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_3_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_3_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_3_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_4 {
            get {
                object obj = ResourceManager.GetObject("White_C_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_4_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_4_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_4_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_4_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_5 {
            get {
                object obj = ResourceManager.GetObject("White_C_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_5_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_5_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_5_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_5_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_6 {
            get {
                object obj = ResourceManager.GetObject("White_C_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_6_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_6_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_6_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_6_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_7 {
            get {
                object obj = ResourceManager.GetObject("White_C_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_7_Last {
            get {
                object obj = ResourceManager.GetObject("White_C_7_Last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_C_7_Possible {
            get {
                object obj = ResourceManager.GetObject("White_C_7_Possible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_K_1 {
            get {
                object obj = ResourceManager.GetObject("White_K_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_K_2 {
            get {
                object obj = ResourceManager.GetObject("White_K_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_K_3 {
            get {
                object obj = ResourceManager.GetObject("White_K_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_K_4 {
            get {
                object obj = ResourceManager.GetObject("White_K_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_K_5 {
            get {
                object obj = ResourceManager.GetObject("White_K_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_N_1 {
            get {
                object obj = ResourceManager.GetObject("White_N_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_N_2 {
            get {
                object obj = ResourceManager.GetObject("White_N_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_N_3 {
            get {
                object obj = ResourceManager.GetObject("White_N_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_N_4 {
            get {
                object obj = ResourceManager.GetObject("White_N_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_N_5 {
            get {
                object obj = ResourceManager.GetObject("White_N_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_P_1 {
            get {
                object obj = ResourceManager.GetObject("White_P_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_P_2 {
            get {
                object obj = ResourceManager.GetObject("White_P_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_P_3 {
            get {
                object obj = ResourceManager.GetObject("White_P_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_P_4 {
            get {
                object obj = ResourceManager.GetObject("White_P_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_P_5 {
            get {
                object obj = ResourceManager.GetObject("White_P_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_Q_1 {
            get {
                object obj = ResourceManager.GetObject("White_Q_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_Q_2 {
            get {
                object obj = ResourceManager.GetObject("White_Q_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_Q_3 {
            get {
                object obj = ResourceManager.GetObject("White_Q_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_Q_4 {
            get {
                object obj = ResourceManager.GetObject("White_Q_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_Q_5 {
            get {
                object obj = ResourceManager.GetObject("White_Q_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_R_1 {
            get {
                object obj = ResourceManager.GetObject("White_R_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_R_2 {
            get {
                object obj = ResourceManager.GetObject("White_R_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_R_3 {
            get {
                object obj = ResourceManager.GetObject("White_R_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_R_4 {
            get {
                object obj = ResourceManager.GetObject("White_R_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_R_5 {
            get {
                object obj = ResourceManager.GetObject("White_R_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
